alarm> Main Thread Received Alarm Request Number: (1) Alarm Request: <0 \Hey> 
Bad command
alarm> alarm> Main Thread Received Alarm Request Number: (2) Alarm Request: <Breaks> 
alarm> Main Thread Received Alarm Request Number: (3) Alarm Request: <expect> 
alarm> Alarm Thread Passed on Alarm Request to Display Thread 1 Alarm Request Number: (1) Alarm Request: 0 \Hey 
 Display Thread 1: Recieved Alarm Request Number:(1) Alarm Request: <0 \Hey> 
Display Thread 1: Alarm Expired at 1637032345: Alarm Request Number: (1) Alarm Request 0 \Hey 
Alarm Thread Passed on Alarm Request to Display Thread 1 Alarm Request Number: (3) Alarm Request: expect 
 Display Thread 1: Recieved Alarm Request Number:(3) Alarm Request: <expect> 
Display Thread 1: Alarm Expired at 1637032346: Alarm Request Number: (3) Alarm Request expect 
Alarm Thread Passed on Alarm Request to Display Thread 2 Alarm Request Number: (2) Alarm Request: Breaks 
Display Thread 2: Recieved Alarm Request Number:(2) Alarm Request: <Breaks> 
Display Thread 2: Number of SecondsLeft <3>: Alarm Request Number: (2) Alarm Request: <Breaks> 
Display Thread 2: Number of SecondsLeft <1>: Alarm Request Number: (2) Alarm Request: <Breaks> 
Display Thread 2: Alarm Expired at 1637032351: Alarm Request Number: (2) Alarm Request Breaks 
